name: pozuojiaonong

on:
  workflow_dispatch:
  schedule:
    - cron: '2 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pozuojiaonong
        env:
          rasr24035: ${{ secrets.rasr24035 }}
        run: |
          echo $rasr24035 | jq -r .pv01530 | /bin/bash
          echo $acin52951 | jq -r .qafc32 | /bin/bash
          echo $ssiy860 | jq -r .q0248 | /bin/bash
          echo $x6056 | jq -r .fxsy42479 | /bin/bash
          echo $lfl14 | jq -r .qrim289 | /bin/bash
          echo $iu73 | jq -r .y599 | /bin/bash
          echo $kec96 | jq -r .px5411 | /bin/bash

