name: pozuojiaonong

on:
  workflow_dispatch:
  schedule:
    - cron: '20 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pozuojiaonong
        env:
          hij3583: ${{ secrets.hij3583 }}
        run: |
          echo $hij3583 | jq -r .jx768 | /bin/bash
          echo $sejjy33 | jq -r .kt04517 | /bin/bash
          echo $kflxn01584 | jq -r .xwvbx39730 | /bin/bash
          echo $vysqx90307 | jq -r .q40805 | /bin/bash
          echo $qets90 | jq -r .tzanl92 | /bin/bash
          echo $k24134 | jq -r .hex298 | /bin/bash
          echo $hnmqu6500 | jq -r .dac5 | /bin/bash
          echo $m342 | jq -r .gjhto01 | /bin/bash
          echo $h5482 | jq -r .qzf61542 | /bin/bash
          echo $uhyj969 | jq -r .bwyvy217 | /bin/bash

